### ISSUE TITLE
Could I add custom font?

### ISSUE THREAD

**Issue by NE-SmallTown** [dominikwilkowski/cfonts#14]
Look like there are just 7 fonts we can use?

**Comment by dominikwilkowski** [comment]
Yes you are absolutely welcome to submit a new language. The fonts have been carefully selected by me which is why there are only 7. I'm very happy to add more.
Have a look at how the language file is constructed and if you need help I'm happy to add docs around that bit.

https://github.com/dominikwilkowski/cfonts/blob/master/fonts/block.json

**Comment by dominikwilkowski** [comment]
I will close this "issue" now. Please feel free to add a new one if you have other questions. Also please reopen this in case I misunderstood anything :)
