### ISSUE TITLE
Rust temp-env 0.3.0

### ISSUE THREAD

**Issue by alcir** [dominikwilkowski/cfonts#61]
https://github.com/dominikwilkowski/cfonts/blob/27f8c680f0be0563000619008efc3b3b069a1415/rust/Cargo.toml#L28

Could there be issues using temp-env 0.3.0?

**Comment by dominikwilkowski** [comment]
Just ran `0.3.0` locally and seems to work fine. I'll push a new version soon but thought I might as well check out other dependencies and update them as well.

Just FYI `temp-env` is a `dev-dependencies` so you should be able to ignore it and run it with your own version unless you're working on a patch?

**Comment by alcir** [comment]
> Just ran `0.3.0` locally and seems to work fine. I'll push a new version soon but thought I kight as well check out other dependencies and update them as well.

Thanks.

> Just FYI `temp-env` is a `dev-dependencies` so you should be able to ignore it and run it with your own version unless you're working on a patch?

I was looking to package rust-cfonts for Fedora. Just for fun.

**Comment by dominikwilkowski** [comment]
Oh that would be cool. Let me know how and where and I include it into the docs. Would need to make sure we can push releases there. Don't know what their process is.

**Comment by dominikwilkowski** [comment]
@alcir any progress on packaging for fedora? I'm keen for help to get this rolled out but don't run fedora myself.

**Comment by alcir** [comment]
Nobody was willing to review the submitted package so far. Let's wait. :crossed_fingers:

**Comment by dominikwilkowski** [comment]
Got a link?

**Comment by alcir** [comment]
Here it is
https://bugzilla.redhat.com/show_bug.cgi?id=2149953

**Comment by dominikwilkowski** [comment]
Let me know if there are any issues you find that should be fixed on my end. The comments look like everything is find on my end anyway. Also how would updates work? Can I push to that new target or do you need to release new versions yourself?

**Comment by alcir** [comment]
Hello.
It seems that the issue is with the LICENSE file. If you read the latest comments, you will understand better than me what I could explain.

**Comment by dominikwilkowski** [comment]
Hey, sorry it took me a bit to get to this. Work has been busy.
I see from the [thread](https://bugzilla.redhat.com/show_bug.cgi?id=2149953) that the license should be changed to `Apache-2.0 AND (Apache-2.0 OR BSL-1.0) AND GPL-3.0-or-later AND ISC AND MIT AND (MIT OR Apache-2.0)`?

I'm curious: How do you submit software to the fedora ecosystem? I want to make sure I can push updates and not have an intermediary in between. And how do they want the license to be changed? I can't make the license change in the cargo.toml file since that would be the wrong license? I assume the change would happen and contained within the fedora ecosystem?

**Comment by decathorpe** [comment]
Hi, reviewer from the linked package review on BugZilla here.

> Hey, sorry it took me a bit to get to this. Work has been busy. I see from the [thread](https://bugzilla.redhat.com/show_bug.cgi?id=2149953) that the license should be changed to `Apache-2.0 AND (Apache-2.0 OR BSL-1.0) AND GPL-3.0-or-later AND ISC AND MIT AND (MIT OR Apache-2.0)`?

No, this is only required for us, since we distribute the binaries. The crate itself doesn't need to do this (and shouldn't) since it only distributes its own source code. The only "problem" about the license is that the LICENSE file is not included in published crates that are redistributed via crates.io (because the LICENSE file is missing from the [package]'s `include` setting in Cargo.toml). Including the project's license file in packages is a hard requirement for us, which is why it's included separately from the crate sources (from GitHub directly) in the current draft of the package.

> I'm curious: How do you submit software to the fedora ecosystem? I want to make sure I can push updates and not have an intermediary in between.

If you want to push updates into Fedora directly, you would need to go through the process of becoming a "trusted" Fedora Packager. I'm not sure if that's what you want though ...

> And how do they want the license to be changed?

The license in the crate metadata is fine, just the `include` is missing `/LICENSE` to also include the license file in published crates.

> I can't make the license change in the cargo.toml file since that would be the wrong license? I assume the change would happen and contained within the fedora ecosystem?

Right, as I explained above, this only affects people who want to distribute *binaries*, not if you only ship this project's source code.

**Comment by dominikwilkowski** [comment]
Hey @decathorpe 
Thank you for taking the time. Appreciate it.

Just fixed the `include` statement in the `Cargo.toml` file.

> If you want to push updates into Fedora directly, you would need to go through the process of becoming a "trusted" Fedora Packager. I'm not sure if that's what you want though ...

I have something similar for AUR at https://aur.archlinux.org/cfonts.git where I can push changes to. What I'm trying to avoid is to have to ask other people when I have a new release. What's the best way here? Happy to do some work to be "trusted"?

**Comment by decathorpe** [comment]
> Hey @decathorpe Thank you for taking the time. Appreciate it.
> 
> Just fixed the `include` statement in the `Cargo.toml` file.

Great, thank you!

> > If you want to push updates into Fedora directly, you would need to go through the process of becoming a "trusted" Fedora Packager. I'm not sure if that's what you want though ...
> 
> I have something similar for AUR at https://aur.archlinux.org/cfonts.git where I can push changes to.

There's a difference between what @alcir is trying to do and what AUR provides. We could provide "first-party" packages (i.e. from the official repositories and not from some community-maintained "extra" thing, like AUR). Fedora has something similar to AUR though (COPR).

The rules for submitting software there are less strict, but the package repositories on COPR need to be enabled manually by people who want to use them (i.e. there's not a single repository, but one for every project). You *could* build cfonts there, but having it in the official repositories removes the need for people to configure package repositories.

> What I'm trying to avoid is to have to ask other people when I have a new release. What's the best way here? Happy to do some work to be "trusted"?

Yeah, I understand what you're worried about here. But usually you wouldn't have to ask anyone - we have an automated system set up that files tickets for all new versions (an example [here](https://bugzilla.redhat.com/show_bug.cgi?id=2227581) that was filed a few hours ago for the latest release of the `time` crate).

You can still follow the process of becoming an official "Packager" for Fedora (documented [here](https://docs.fedoraproject.org/en-US/package-maintainers/Joining_the_Package_Maintainers/)), though by submitting the package for review, @alcir would already take on the responsibility of keeping the package up-to-date.

**Comment by alcir** [comment]
Hello @dominikwilkowski 
When do you plan to release a new version with the latest patches included?
Thanks.

**Comment by dominikwilkowski** [comment]
Hey @alcir 
I'm just about to go on vacation for a week. Either during or after. I'm trying to batch a couple other dep updates into this release as releases take time for rust.

While we're on the topic, how would you like to manage the release to the Fedora ecosystem? If I have a new release out, how do I ping you to release there too? I'd love to make sure if a release goes out it's available shortly on all platforms.

**Comment by decathorpe** [comment]
Once release-monitoring.org is set up for this project, we will get a ticket filed for all new versions automatically (assuming you publish them on crates.io or tag them on GitHub, preferably both).

**Comment by dominikwilkowski** [comment]
Perfect. I had missed that earlier.

**Comment by dominikwilkowski** [comment]
@alcir v1.1.1rust has been published. It's still in the pipes with homebrew and other dist channels but it's now live on the github release and via crates.io

**Comment by dominikwilkowski** [comment]
Closing this issue now since `temp-env` is now at `0.3` via [@dominikwilkowski/cfonts/blob/released/rust/Cargo.toml#L28](https://github.com/dominikwilkowski/cfonts/blob/34146ffb56375f0cd35a39169bc6903ff81c7fd4/rust/Cargo.toml#L28).

Also the License is now included in the cargo release via:
```sh
λ cargo package --list --allow-dirty
Cargo.lock
Cargo.toml
Cargo.toml.orig
LICENSE
README.md
fonts/3d.json
fonts/block.json
fonts/chrome.json
fonts/console.json
fonts/grid.json
fonts/huge.json
fonts/pallet.json
fonts/shade.json
fonts/simple.json
fonts/simple3d.json
fonts/simpleBlock.json
fonts/slick.json
fonts/tiny.json
src/args.rs
src/chars.rs
src/cli.rs
src/color.rs
src/config.rs
src/debug.rs
src/font.rs
src/gradient.rs
src/helpers.rs
src/lib.rs
src/main.rs
src/render.rs
```
You can also verify what's actually inside the tar ball on crates.io by downloading this file https://crates.io/api/v1/crates/cfonts/1.1.2/download, renaming it to `*.tar` and unpack it:
```sh
λ wget https://crates.io/api/v1/crates/cfonts/1.1.2/download -O cfonts.tar
[...]
λ tar -xf cfonts.tar 
λ ls cfonts-1.1.2/
Cargo.lock	Cargo.toml	Cargo.toml.orig	LICENSE		README.md	fonts		src
```

**Comment by decathorpe** [comment]
Great, thank you!
